# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication.proto',
  package='communcation',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63ommunication.proto\x12\x0c\x63ommuncation\"#\n\x07RawSend\x12\r\n\x05raw_x\x18\x01 \x01(\x0c\x12\t\n\x01Y\x18\x02 \x01(\x0c\"\x1a\n\x08RawReply\x12\x0e\n\x06signal\x18\x01 \x01(\x0c\"\'\n\nOutputSend\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x12\t\n\x01Y\x18\x02 \x01(\x0c\"\x1c\n\x0bOutputReply\x12\r\n\x05grads\x18\x01 \x01(\x0c\"Q\n\tGradsSend\x12\x0f\n\x07grads_w\x18\x01 \x01(\x0c\x12\x12\n\ngrads_bias\x18\x02 \x01(\x0c\x12\x11\n\tlayer_num\x18\x03 \x01(\x0c\x12\x0c\n\x04name\x18\x04 \x01(\x0c\"1\n\nGradsReply\x12\x0f\n\x07grads_w\x18\x01 \x01(\x0c\x12\x12\n\ngrads_bias\x18\x02 \x01(\x0c\"\x18\n\x06Singal\x12\x0e\n\x06singal\x18\x01 \x01(\x0c\x32\xd3\x03\n\x04\x43omm\x12\x43\n\x10process_raw_data\x12\x15.communcation.RawSend\x1a\x16.communcation.RawReply\"\x00\x12N\n\x15process_device_output\x12\x18.communcation.OutputSend\x1a\x19.communcation.OutputReply\"\x00\x12N\n\x17get_one_layer_gradients\x12\x17.communcation.GradsSend\x1a\x18.communcation.GradsReply\"\x00\x12M\n\x14process_cloud_output\x12\x18.communcation.OutputSend\x1a\x19.communcation.OutputReply\"\x00\x12H\n\x18get_singal_for_new_epoch\x12\x14.communcation.Singal\x1a\x14.communcation.Singal\"\x00\x12M\n\x1dget_singal_for_finished_epoch\x12\x14.communcation.Singal\x1a\x14.communcation.Singal\"\x00\x62\x06proto3')
)




_RAWSEND = _descriptor.Descriptor(
  name='RawSend',
  full_name='communcation.RawSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_x', full_name='communcation.RawSend.raw_x', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Y', full_name='communcation.RawSend.Y', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=72,
)


_RAWREPLY = _descriptor.Descriptor(
  name='RawReply',
  full_name='communcation.RawReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='communcation.RawReply.signal', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=100,
)


_OUTPUTSEND = _descriptor.Descriptor(
  name='OutputSend',
  full_name='communcation.OutputSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='communcation.OutputSend.output', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Y', full_name='communcation.OutputSend.Y', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=141,
)


_OUTPUTREPLY = _descriptor.Descriptor(
  name='OutputReply',
  full_name='communcation.OutputReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grads', full_name='communcation.OutputReply.grads', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=171,
)


_GRADSSEND = _descriptor.Descriptor(
  name='GradsSend',
  full_name='communcation.GradsSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grads_w', full_name='communcation.GradsSend.grads_w', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grads_bias', full_name='communcation.GradsSend.grads_bias', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_num', full_name='communcation.GradsSend.layer_num', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='communcation.GradsSend.name', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=254,
)


_GRADSREPLY = _descriptor.Descriptor(
  name='GradsReply',
  full_name='communcation.GradsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grads_w', full_name='communcation.GradsReply.grads_w', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grads_bias', full_name='communcation.GradsReply.grads_bias', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=305,
)


_SINGAL = _descriptor.Descriptor(
  name='Singal',
  full_name='communcation.Singal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='singal', full_name='communcation.Singal.singal', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=331,
)

DESCRIPTOR.message_types_by_name['RawSend'] = _RAWSEND
DESCRIPTOR.message_types_by_name['RawReply'] = _RAWREPLY
DESCRIPTOR.message_types_by_name['OutputSend'] = _OUTPUTSEND
DESCRIPTOR.message_types_by_name['OutputReply'] = _OUTPUTREPLY
DESCRIPTOR.message_types_by_name['GradsSend'] = _GRADSSEND
DESCRIPTOR.message_types_by_name['GradsReply'] = _GRADSREPLY
DESCRIPTOR.message_types_by_name['Singal'] = _SINGAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RawSend = _reflection.GeneratedProtocolMessageType('RawSend', (_message.Message,), dict(
  DESCRIPTOR = _RAWSEND,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communcation.RawSend)
  ))
_sym_db.RegisterMessage(RawSend)

RawReply = _reflection.GeneratedProtocolMessageType('RawReply', (_message.Message,), dict(
  DESCRIPTOR = _RAWREPLY,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communcation.RawReply)
  ))
_sym_db.RegisterMessage(RawReply)

OutputSend = _reflection.GeneratedProtocolMessageType('OutputSend', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTSEND,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communcation.OutputSend)
  ))
_sym_db.RegisterMessage(OutputSend)

OutputReply = _reflection.GeneratedProtocolMessageType('OutputReply', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTREPLY,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communcation.OutputReply)
  ))
_sym_db.RegisterMessage(OutputReply)

GradsSend = _reflection.GeneratedProtocolMessageType('GradsSend', (_message.Message,), dict(
  DESCRIPTOR = _GRADSSEND,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communcation.GradsSend)
  ))
_sym_db.RegisterMessage(GradsSend)

GradsReply = _reflection.GeneratedProtocolMessageType('GradsReply', (_message.Message,), dict(
  DESCRIPTOR = _GRADSREPLY,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communcation.GradsReply)
  ))
_sym_db.RegisterMessage(GradsReply)

Singal = _reflection.GeneratedProtocolMessageType('Singal', (_message.Message,), dict(
  DESCRIPTOR = _SINGAL,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communcation.Singal)
  ))
_sym_db.RegisterMessage(Singal)



_COMM = _descriptor.ServiceDescriptor(
  name='Comm',
  full_name='communcation.Comm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=334,
  serialized_end=801,
  methods=[
  _descriptor.MethodDescriptor(
    name='process_raw_data',
    full_name='communcation.Comm.process_raw_data',
    index=0,
    containing_service=None,
    input_type=_RAWSEND,
    output_type=_RAWREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='process_device_output',
    full_name='communcation.Comm.process_device_output',
    index=1,
    containing_service=None,
    input_type=_OUTPUTSEND,
    output_type=_OUTPUTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_one_layer_gradients',
    full_name='communcation.Comm.get_one_layer_gradients',
    index=2,
    containing_service=None,
    input_type=_GRADSSEND,
    output_type=_GRADSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='process_cloud_output',
    full_name='communcation.Comm.process_cloud_output',
    index=3,
    containing_service=None,
    input_type=_OUTPUTSEND,
    output_type=_OUTPUTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_singal_for_new_epoch',
    full_name='communcation.Comm.get_singal_for_new_epoch',
    index=4,
    containing_service=None,
    input_type=_SINGAL,
    output_type=_SINGAL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_singal_for_finished_epoch',
    full_name='communcation.Comm.get_singal_for_finished_epoch',
    index=5,
    containing_service=None,
    input_type=_SINGAL,
    output_type=_SINGAL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMM)

DESCRIPTOR.services_by_name['Comm'] = _COMM

# @@protoc_insertion_point(module_scope)
