# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import communication_pb2 as communication__pb2


class CommStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process_raw_data = channel.unary_unary(
        '/communcation.Comm/process_raw_data',
        request_serializer=communication__pb2.RawSend.SerializeToString,
        response_deserializer=communication__pb2.RawReply.FromString,
        )
    self.process_device_output = channel.unary_unary(
        '/communcation.Comm/process_device_output',
        request_serializer=communication__pb2.OutputSend.SerializeToString,
        response_deserializer=communication__pb2.OutputReply.FromString,
        )
    self.get_one_layer_gradients = channel.unary_unary(
        '/communcation.Comm/get_one_layer_gradients',
        request_serializer=communication__pb2.GradsSend.SerializeToString,
        response_deserializer=communication__pb2.GradsReply.FromString,
        )
    self.process_cloud_output = channel.unary_unary(
        '/communcation.Comm/process_cloud_output',
        request_serializer=communication__pb2.OutputSend.SerializeToString,
        response_deserializer=communication__pb2.OutputReply.FromString,
        )
    self.get_singal_for_new_epoch = channel.unary_unary(
        '/communcation.Comm/get_singal_for_new_epoch',
        request_serializer=communication__pb2.Singal.SerializeToString,
        response_deserializer=communication__pb2.Singal.FromString,
        )
    self.get_singal_for_finished_epoch = channel.unary_unary(
        '/communcation.Comm/get_singal_for_finished_epoch',
        request_serializer=communication__pb2.Singal.SerializeToString,
        response_deserializer=communication__pb2.Singal.FromString,
        )


class CommServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def process_raw_data(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def process_device_output(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_one_layer_gradients(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def process_cloud_output(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_singal_for_new_epoch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_singal_for_finished_epoch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process_raw_data': grpc.unary_unary_rpc_method_handler(
          servicer.process_raw_data,
          request_deserializer=communication__pb2.RawSend.FromString,
          response_serializer=communication__pb2.RawReply.SerializeToString,
      ),
      'process_device_output': grpc.unary_unary_rpc_method_handler(
          servicer.process_device_output,
          request_deserializer=communication__pb2.OutputSend.FromString,
          response_serializer=communication__pb2.OutputReply.SerializeToString,
      ),
      'get_one_layer_gradients': grpc.unary_unary_rpc_method_handler(
          servicer.get_one_layer_gradients,
          request_deserializer=communication__pb2.GradsSend.FromString,
          response_serializer=communication__pb2.GradsReply.SerializeToString,
      ),
      'process_cloud_output': grpc.unary_unary_rpc_method_handler(
          servicer.process_cloud_output,
          request_deserializer=communication__pb2.OutputSend.FromString,
          response_serializer=communication__pb2.OutputReply.SerializeToString,
      ),
      'get_singal_for_new_epoch': grpc.unary_unary_rpc_method_handler(
          servicer.get_singal_for_new_epoch,
          request_deserializer=communication__pb2.Singal.FromString,
          response_serializer=communication__pb2.Singal.SerializeToString,
      ),
      'get_singal_for_finished_epoch': grpc.unary_unary_rpc_method_handler(
          servicer.get_singal_for_finished_epoch,
          request_deserializer=communication__pb2.Singal.FromString,
          response_serializer=communication__pb2.Singal.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'communcation.Comm', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
