# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import communication_pb2 as communication__pb2


class CommStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Forwarding = channel.unary_unary(
        '/communcation.Comm/Forwarding',
        request_serializer=communication__pb2.ArrayRecv.SerializeToString,
        response_deserializer=communication__pb2.ArrayReply.FromString,
        )
    self.Data_paralle = channel.unary_unary(
        '/communcation.Comm/Data_paralle',
        request_serializer=communication__pb2.ArrayRecv1.SerializeToString,
        response_deserializer=communication__pb2.ArrayReply.FromString,
        )


class CommServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Forwarding(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Data_paralle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Forwarding': grpc.unary_unary_rpc_method_handler(
          servicer.Forwarding,
          request_deserializer=communication__pb2.ArrayRecv.FromString,
          response_serializer=communication__pb2.ArrayReply.SerializeToString,
      ),
      'Data_paralle': grpc.unary_unary_rpc_method_handler(
          servicer.Data_paralle,
          request_deserializer=communication__pb2.ArrayRecv1.FromString,
          response_serializer=communication__pb2.ArrayReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'communcation.Comm', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
